<a href="https://colab.research.google.com/github/chimieee/Linear_Algebra_ChE_2nd_Sem_2021_2022/blob/main/Matrix_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE
##Assignment 3: Matrices



We'll try to look into further depth keeping in mind the basic understanding of Python.



###Objectives
At the end of this activity you will be able to:
1. Perform basic matrix computations. 
2. Understand matrices and how they relate to linear equations. 
3. Interpret and utilize matrix equations and operations.

# Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

:$$
A=\begin{bmatrix}\ 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix}\ 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end
{bmatrix}\\
C=\begin{bmatrix}\ 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix} 
$$




In [ ]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 4 x 5 matrix
L = np.array ([
    [96, 68, 33, 39, 51],
    [60, 19 ,30, 45, 86],
    [62, 57, 68, 93, 31],
    [57, 23, 19, 58, 23]
])
describe_mat(L)

Matrix:
[[96 68 33 39 51]
 [60 19 30 45 86]
 [62 57 68 93 31]
 [57 23 19 58 23]]

Shape:	(4, 5)
Rank:	2



In [ ]:
N = np.array([[[
    [31, 32, 33, 34, 35],
    [41, 42, 53, 53, 13],
    [71, 24, 65, 73, 31],
    [31, 89, 13, 54, 14]
]]])
describe_mat(N)

Matrix:
[[[[31 32 33 34 35]
   [41 42 53 53 13]
   [71 24 65 73 31]
   [31 89 13 54 14]]]]

Shape:	(1, 1, 4, 5)
Rank:	4



In [ ]:
E = np.array([
    [81, 92, 73, 44, 35],
    [11, 22, 13, 63, 73],
    [71, 54, 45, 23, 41],
    [71, 89, 13, 84, 34]
])
describe_mat(E)

Matrix:
[[81 92 73 44 35]
 [11 22 13 63 73]
 [71 54 45 23 41]
 [71 89 13 84 34]]

Shape:	(4, 5)
Rank:	2



In [ ]:
A = np.array([
    [32, 34, 37, 32, 36],
    [41, 42, 57, 52, 13],
    [71, 24, 65, 73, 31],
    [31, 89, 13, 54, 14]
])
describe_mat(A)

Matrix:
[[32 34 37 32 36]
 [41 42 57 52 13]
 [71 24 65 73 31]
 [31 89 13 54 14]]

Shape:	(4, 5)
Rank:	2



In [ ]:
R = np.array([
    [31, 32, 33, 34, 35],
    [43, 42, 50, 57, 13],
    [72, 24, 65, 73, 39],
    [51, 89, 13, 74, 54]
  ]) 
describe_mat(R)


Matrix:
[[31 32 33 34 35]
 [43 42 50 57 13]
 [72 24 65 73 39]
 [51 89 13 74 54]]

Shape:	(4, 5)
Rank:	2



## Categorizing Matrices

In [ ]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    5, 10, 15
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [10,20,30]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[ 5 10 15]

Shape:	(3,)
Rank:	1

Matrix:
[[10 20 30]]

Shape:	(1, 3)
Rank:	2



In [ ]:
## Declaring a column matrix

colmat = np.array([
    [3],
    [5],
    [7]
]) ## This is a 2-D Matrix with a shape of (3, 1)
describe_mat(colmat)

##### Square Matrix
Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if . We can tweak our matrix descriptor function to determine square matrices.

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False                                                     
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
  [5, 3, 2, 1],
  [3, 2, 4, 9],
  [8, 4, 7, 5],
  [4, 8, 9, 1]
])
not_square_mat = np.array([
  [3, 4, 1, 4],
  [9, 6, 1, 3]
])
describe_mat (square_mat)
describe_mat (not_square_mat)

##### Null Matrix
A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [ ]:
def describe_mat(matrix):
  if matrix.size > 0:
    is_square - True if matrix.shape[0] -- matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else:
    print('Matrix is Null.')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

##### Zero Matrix

In [ ]:
zero_mat_row = np.zeros ((1,2))
zero_mat_sqr = np.zeros ((2,2))
zero_mat_rct = np.zeros ((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

####Ones Matrix


In [ ]:
## Ones Matrix -  to get the identity

ones_mat_row = np.ones ((1,2))
ones_mat_sqr = np.ones ((2,2))
ones_mat_rct = np.ones ((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

#### Diagonal Matrix


In [ ]:
## Diagonal Matrix
np.array([
   [2, 0, 0],
   [0, 2, 0],
   [0, 0, 2]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1, n-1]

In [ ]:
#Other way to declare a diagonal matrix
d = np.diag([1, 9, 9, 7])
d

####Identity Matrix

In [ ]:
#Identity Matrix
np.eye(3)

In [ ]:
#Other way to Declare an Identity Matrix
np.identity(7)

####Upper Triangular Matrix

In [ ]:
#Upper Triangular Matrix
np.array([
  [9, 0, 0, 0],
  [1, 3, 0, 0],
  [5, 3, 1, 0],
  [1, 3, 6, 8]
])

In [ ]:
#Other Way to Declare Upper Triangular Matrix 
M = np.array([
    [32, -65, 15, -69, 20],
    [32, -65, 15, -69, 20],
    [32, -65, 15, -69, 20],
    [32, -65, 15, -69, 20],
    [32, -65, 15, -69, 20]
])
np. triu(E)


####Lower Triangular Matrix

In [ ]:
#Lower Triangular Matrix 
np.array([
  [42, 0, 0, 0],
  [69, 42, 0, 0,],
  [69, 42, 42, 0],
  [69, 69, 69, 69]
])

In [ ]:
#Other Way to Declare a Lower Triangular Matrix
np.tril (M)

#Practice

Given the linear combination below, try to create a corresponding matrix representing it.

$$
\theta = 5x + 3y -z
$$

Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{
    \begin{array}\
    x_1 + 2x_2 + x_3 \\
    4x_2 - x_3 \\
    10x_3
    \end{array}
\right. 
$$

In [ ]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')
A = np.array ([
    [1, 2, 1],
    [-1, 4, 0],
    [10, 0 ,0]
])
A
describe_mat(A)

Given the matrix below, express it as a linear combination in a markdown.

G = np.array([ <br>
    [1,7,8], <br>
    [2,2,2], <br>
    [4,6,7] <br>
])

:$$
G=\begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 &7\end{bmatrix} \\
$$


$$
G = \left\{
    \begin{array}\
    x_1 + 7x_2 + 8x_3\\
    2x_1 + 2x_2 + 2x_3 \\
    4x_1 + 6x_2 + 7x_3
    \end{array}
\right. 
$$

Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations. <br>
H = np.tril(G) <br>
H

array([[1, 0, 0], <br>
       [2, 2, 0], <br>
       [4, 6, 7]]) <br>

:$$
H=\begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 &7\end{bmatrix} \\
$$

$$
H = \left\{
    \begin{array}\
    x_1  \\
    2x_1 - 2x_2 \\
    4x_1 + 6x_2 + 7x_3
    \end{array}
\right. 
$$

#### Matrix Algebra



#####Addition

In [ ]:
#Declaring Matrix M and J and Addition of Matrices
M = np.array([
     [8, 24],
     [5, 0],
     [32, 10]
])
J = np.array([
     [12, 15],
     [0, 0],
     [23, 65]
])
M+J

In [ ]:
3+M ####Broadcasting
#3*np.ones(J.shape)+M

In [ ]:
#Other Way to Perform Addition of Matrices
np.add(M,J)

#####Subtraction

In [ ]:
#Subtraction of Matrices
M-J

In [ ]:
2-M
#2*np.ones(M.shape)-J

#####Element-wise Multiplication

In [ ]:
#Element-wise Multiplication
M*J
#np.multiply(M,J)

#####Element-wise Division

In [ ]:
#Element-wise Division
M/J

In [ ]:
#Division Involving Matrices
omega=10**-2
M/(omega+J)

#Activity
This part is where we are given an output that involves our learnings about Matrices in Python

####Task 1
Create a function named mat_desc() that througouhly describes a matrix, it should:

Displays the shape, size, and rank of the matrix.<br>
Displays whether the matrix is square or non-square.<br>
Displays whether the matrix is an empty matrix.<br>
Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
## Function Area 
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline
def describe_mat(matrix):
  if matrix.size > 0:
    if matrix.shape[0] == matrix.shape[1]:
      is_square = True
    else: 
      is_square = False
    if np.all(matrix == np.identity(matrix.shape[0])):
      sp = "Identity Matrix"
    elif np.all(matrix == np.zeros(matrix.shape)):
      sp = "Zero Matrix."
    elif np.all(matrix == np.ones(matrix.shape)):
      sp = "Ones Matrix."
    else:
      sp = "None."
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else:
    print('Matrix is Null.')
  
    

In [ ]:
## Matrix Declarations
L = np.array([[[[
    [96, 68, 33, 39, 51],
    [60, 19 ,30, 45, 86],
    [62, 57, 68, 93, 31],
    [57, 23, 19, 58, 23]
]]]])

N = np.array([[[
    [31, 32, 33, 34, 35],
    [41, 42, 53, 53, 13],
    [71, 24, 65, 73, 31],
    [31, 89, 13, 54, 14]
]]])

E = np.array([[
    [81, 92, 73, 44, 35],
    [11, 22, 13, 63, 73],
    [71, 54, 45, 23, 41],
    [71, 89, 13, 84, 34]
]])

A = np.array([
    [32, 34, 37, 32, 36],
    [41, 42, 57, 52, 13],
    [71, 24, 65, 73, 31],
    [31, 89, 13, 54, 14]
])

R = np.array([
    [31, 32, 33, 34, 35],
    [43, 42, 50, 57, 13],
    [72, 24, 65, 73, 39],
    [51, 89, 13, 74, 54]
  ]) 

In [ ]:
## Test Areas 

describe_mat(L)

describe_mat(N)

describe_mat(E)

describe_mat(A)

describe_mat(R)

###Task 2
Create a function named mat_operations() that takes in two matrices a input parameters it should:

Determines if the matrices are viable for operation and returns your own error message if they are not viable.<br>
Returns the sum of the matrices.<br>
Returns the differen of the matrices.<br>
Returns the element-wise multiplication of the matrices.<br>

Returns the element-wise division of the matrices.
Use 5 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
## Function Area
import numpy as np
def mat_operation(L, N):
  print(f'Matrix 1:\n {M} \n')
  print(f'Matrix 2:\n {J} \n')


  if(M.shape != J.shape):
    print('The shape of both matrices are not same. The system could not perform any operation.')
    return

  plus = M + J
  print(f'Sum of the chosen matrices:\n {plus} \n')

  minus = M - J
  print(f'Difference of the chosen matrices:\n {minus} \n')

  matpro = np.multiply(M, J)
  print(f'Element-wise multiplication of the chosen matrices:\n {matpro} \n')

  matdiv = np.divide(M, J)
  print(f'Element-wise division of the chosen matrices:\n {matdiv} \n')

In [ ]:
## Matrix Declarations
M = np.array([
     [8, 24],
     [5, 0],
     [32, 10]
])
J = np.array([
     [12, 15],
     [0, 0],
     [23, 65]
])

In [ ]:
## Test Areas
mat_operation(M, J)

#Conclusion
In mathematics and other fields, matrix operations are commonly employed. It can be used to solve linear equations. They can be used to solve problems concerning dynamics, motion equations, and other topics. They're useful in sensor array signal processing and adaptive filter construction. Matrices are useful for processing and displaying digital images. They can also be used to simulate and optimize wireless transmissions. Extraction and processing of information encoded in signal matrices are employed for detection. Signal estimation and detection problems rely heavily on matrices.	
	Matrices are useful tools for resolving technological issues. Image processing, genetic research, and other relationships in measurements of qualities such as temperature and pressure are examples of practical applications of matrices. Matrices are also employed in graphics, where each pixel is represented by an element in a matrix, and decoding digital films is accomplished by multiplying matrices; researchers were able to develop video-coding circuits as a result of this finding. These can be accomplished by converting data and systems of equations into matrices and conducting operations on them to quickly calculate approximations to difficult issues.
	During the session, students were also able to understand and comprehend the many types of matrices and operations in the Python Programming Language. Students improve their knowledge and skills by writing two programs: one that defines the shape, size, and rank of a matrices and another that describes the viability of two matrices.
