<a href="https://colab.research.google.com/github/chimieee/Linear_Algebra_ChE_2nd_Sem_2021_2022/blob/main/Matrix_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE
##Assignment 3: Matrices



We'll try to look into further depth keeping in mind the basic understanding of Python.



###Objectives
At the end of this activity you will be able to:
1. Perform basic matrix computations. 
2. Understand matrices and how they relate to linear equations. 
3. Interpret and utilize matrix equations and operations.

# Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

:$$
A=\begin{bmatrix}\ 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix}\ 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end
{bmatrix}\\
C=\begin{bmatrix}\ 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix} 
$$




In [ ]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 4 x 5 matrix
L = np.array ([
    [96, 68, 33, 39, 51],
    [60, 19 ,30, 45, 86],
    [62, 57, 68, 93, 31],
    [57, 23, 19, 58, 23]
])
describe_mat(L)

Matrix:
[[96 68 33 39 51]
 [60 19 30 45 86]
 [62 57 68 93 31]
 [57 23 19 58 23]]

Shape:	(4, 5)
Rank:	2



In [ ]:
N = np.array([[[
    [31, 32, 33, 34, 35],
    [41, 42, 53, 53, 13],
    [71, 24, 65, 73, 31],
    [31, 89, 13, 54, 14]
]]])
describe_mat(N)

Matrix:
[[[[31 32 33 34 35]
   [41 42 53 53 13]
   [71 24 65 73 31]
   [31 89 13 54 14]]]]

Shape:	(1, 1, 4, 5)
Rank:	4



In [ ]:
E = np.array([
    [81, 92, 73, 44, 35],
    [11, 22, 13, 63, 73],
    [71, 54, 45, 23, 41],
    [71, 89, 13, 84, 34]
])
describe_mat(E)

Matrix:
[[81 92 73 44 35]
 [11 22 13 63 73]
 [71 54 45 23 41]
 [71 89 13 84 34]]

Shape:	(4, 5)
Rank:	2



In [ ]:
A = np.array([
    [32, 34, 37, 32, 36],
    [41, 42, 57, 52, 13],
    [71, 24, 65, 73, 31],
    [31, 89, 13, 54, 14]
])
describe_mat(A)

Matrix:
[[32 34 37 32 36]
 [41 42 57 52 13]
 [71 24 65 73 31]
 [31 89 13 54 14]]

Shape:	(4, 5)
Rank:	2



In [ ]:
R = np.array([
    [31, 32, 33, 34, 35],
    [43, 42, 50, 57, 13],
    [72, 24, 65, 73, 39],
    [51, 89, 13, 74, 54]
  ]) 
describe_mat(R)


Matrix:
[[31 32 33 34 35]
 [43 42 50 57 13]
 [72 24 65 73 39]
 [51 89 13 74 54]]

Shape:	(4, 5)
Rank:	2



## Categorizing Matrices

In [ ]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    5, 10, 15
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [10,20,30]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[ 5 10 15]

Shape:	(3,)
Rank:	1

Matrix:
[[10 20 30]]

Shape:	(1, 3)
Rank:	2



In [ ]:
## Declaring a column matrix

colmat = np.array([
    [3],
    [5],
    [7]
]) ## This is a 2-D Matrix with a shape of (3, 1)
describe_mat(colmat)

##### Square Matrix
Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if . We can tweak our matrix descriptor function to determine square matrices.

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False                                                     
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
  [5, 3, 2, 1],
  [3, 2, 4, 9],
  [8, 4, 7, 5],
  [4, 8, 9, 1]
])
not_square_mat = np.array([
  [3, 4, 1, 4],
  [9, 6, 1, 3]
])
describe_mat (square_mat)
describe_mat (not_square_mat)

##### Null Matrix
A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [ ]:
def describe_mat(matrix):
  if matrix.size > 0:
    is_square - True if matrix.shape[0] -- matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else:
    print('Matrix is Null.')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

##### Zero Matrix

In [ ]:
zero_mat_row = np.zeros ((1,2))
zero_mat_sqr = np.zeros ((2,2))
zero_mat_rct = np.zeros ((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')